name: geojson_fields
description: A package to parse incoming json MultiPointFields, MultiPolygonFields, MultiLineFields.
version: 0.0.2
homepage: https://github.com/asks8m/geojson_fields

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
